language: python

python: "3.6"

env:
  - TOXENV=py36

install:
  - pip install .[dev]
  - pip install -U tox

script:
  - tox

# to test for Python 3.5
#matrix:
#  include:
#    - python: 3.5
#      env:
#      - TOXENV=py35
